version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/prod.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Persist SQLite database
      - ./data:/app/data
      # Persist logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/consumables"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
